---
- name: Install certbot with the apache plugin
  apt: >
    upgrade=yes
    update_cache=yes
    cache_valid_time=3600  

  - name: Install base packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
    - cerbot

- name: Enable Certbot Apache
  command: apt-get install python-certbot-apache -t stretch-backports

