---

- name: Install certbot
  apt:
    name: certbot
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Enable Certbot Apache
  command: apt-get install -y python-certbot-apache -t stretch-backports
